dependencies:
- name: postgresql
  version: ~7.7.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.install

- name: redis
  version: ~10.2.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.install

- name: rabbitmq
  version: ~6.14.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.install
