---
apiVersion: v1

version: "1.2.0"
appVersion: "0.26.0"

name: rasa-x
description: Rasa X Helm chart for Kubernetes / Openshift
home: https://github.com/RasaHQ/rasa-x-helm

icon: "https://rasa.com/static/rasa-logo-square-ef3444fc36faec97ae8bd7bfb568996d.svg"

keywords:
- "Rasa"
- "AI Assistants"
- "Chatbot"
- "Rasa X"

maintainers:
- name: "tmbo"
  email: "tom@rasa.com"
  url: "https://rasa.com"

dependencies:
- name: postgresql
  version: ~7.7.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.install

- name: redis
  version: ~10.2.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.install

- name: rabbitmq
  version: ~6.14.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.install
