name: Release Charts

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # See https://github.com/helm/chart-releaser-action/issues/6
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Add dependency chart repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.1.0
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"

    - name: Generate Changelog
      uses: scottbrenner/generate-changelog-action@1.0.1
      id: changelog
      env:
        REPO: ${{ github.repository }}

    - name: Update Release body
      # check if there is changelog
      if: startsWith(steps.changelog.outputs.changelog, '####')
      run: |
        # Get release id
        RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq '.id')

        RELEASE_BODY="${{ steps.changelog.outputs.changelog }}"
        RELEASE_BODY="${RELEASE_BODY//$'\n'/'\n'}"

        # Update release body
        curl -X PATCH -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}" \
          -d "{\"body\":\"$RELEASE_BODY\"}"
